### ISSUE TITLE
MINE, correlation plot

### ISSUE THREAD

**Issue by rahulnccs** [minepy/minepy#10]
Dear all,
We tried to implement MINE method to our dataset, we generated the table representing Pearson rank, MIC rank and  MIC. But due to lack in expertise in computer language we are unable to visualize which bacteria(OTUs) are enriching in disease state and which are there reducing in disease/healthy condition. Kindly reply to the mail. Our lab will appreciate you help.

Please do reply

**Comment by davidealbanese** [comment]
The minepy library does not implement any visualization tool. I suggest to use R (e.g. ggplot2) or Python (matplotlib).
