### ISSUE TITLE
Can this project supports CUDA?

### ISSUE THREAD

**Issue by zhenpingfeng** [minepy/minepy#11]
Too slow when computing big element. Is possible make this project running on GPUs to speed up?

**Comment by davidealbanese** [comment]
Dear @zhenpingfeng, what do you mean by "big element"?

**Comment by raqueldias** [comment]
I have the same issue. I have 2 arrays of shape 30000x1682, MIC calaculation gets really slow and unfeasible in such cases, it could benefit of GPUs to improve performance.

**Comment by GF-Huang** [comment]
Any news?
