### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by rgommers** [minepy/minepy#13]
This project doesn't run under Python 3, which is what most users will have installed nowadays. Is there a plan to add Python 3 support? I'd be happy to help test at least (not sure I have time to do more).

**Comment by davidealbanese** [comment]
Dear @rgommers,
could you explain what problems you have encountered with Python 3?

**Comment by rgommers** [comment]
Just following the doc examples (http://minepy.readthedocs.io/en/latest/application.html#examples) immediately runs into non-py3k `print` statements and `except`s (e.g. https://github.com/minepy/minepy/blob/master/minepy/scripts/mine#L94); those examples clearly have never run under Python 3. After fixing the first 4 or so I kept on running into new ones, so decided to open an issue instead.

**Comment by davidealbanese** [comment]
The mine command line application `mine` is obsolete and was removed in version 1.2.2. Now the minepy Python interface is fully compatible with Python 2/3.
