### ISSUE TITLE
Differences between the TICe values delivered by minepy and by MINEv2.jar

### ISSUE THREAD

**Issue by cs224** [minepy/minepy#15]
I've created a jupyter notebook to demonstrate the issue: https://nbviewer.jupyter.org/gist/cs224/7def52c3655ac7f2abfa64f2aff3722b

I've used the first example of minepy (the sine wave without noise) and calculated TICe and MICe via minepy and MINEv2.jar from here: http://www.exploredata.net/Usage-instructions

The MICe values agree reasonably well: 0.91567 vs. 0.913464 (MINEv2.jar vs. minepy)

But the TICe value differ very much: 0.87916 vs. 0.4354463

I am not sure if I am using the tools wrong or if there is a bug in the implementation or an intended difference in implementation? Could you please clarify?

Thanks,
Christian

**Comment by davidealbanese** [comment]
Dear Christian,
as you can see in the `MINEv2.jar` output, the value of alpha chosen for TIC<sub>e</sub> is 0.334, not 0.75. So:
```python
>>> mine_e = minepy.MINE(alpha=0.334, c=5, est="mic_e")
>>> mine_e.compute_score(x, y)
>>> mine_e.tic()
0.8685195257475813
```
In `mictools null` command the parameter is expressed as the maximum grid size (`-b/--grid`, default 9) and in this case it will be 1000^0.334 ~ 10.

Note that the TIC value reported by `MINEv2.jar` is not normalized.

### An example with 10000 samples

```python
>>> x = np.linspace(0, 1, 10000)
>>> y = np.sin(10 * np.pi * x) + x
```
`MINEv2.jar`
```sh
....
Analysis Parameters...
MIC estimator = MICe
alpha = 0.6
numClumpsFactor = 1
alphaTICe = 0,302
debug level = 0
...
```
TIC<sub>e</sub>: 1.6990501

`minepy`
```python
>>> mine_e = minepy.MINE(alpha=0.302, c=1, est="mic_e")
>>> mine_e.compute_score(x, y)
>>> mine_e.tic()
1.4122335714473038
```



I hope this helps,
Davide

**Comment by cs224** [comment]
Thank you very much for your quick response and helpful answer!
