### ISSUE TITLE
Installation issue on Anaconda with Windows

### ISSUE THREAD

**Issue by rverma07** [minepy/minepy#17]
Hello,
Is this package not supported on windows? I am trying to install on Anaconda fails with error code 1. I tried suggestion by an earlier user to "conda uninstall libpython" before installation, but it still fails. Any suggestion is welcome!
Thanks!

**Comment by davidealbanese** [comment]
You can use minepy on MS Windows installing Docker and the mictools docker image (https://hub.docker.com/r/minepy/mictools).
