### ISSUE TITLE
Question on MIC/TIC applied to variables with different lengths

### ISSUE THREAD

**Issue by ivan-marroquin** [minepy/minepy#24]
Hi,

I have the following question: 

there are two variables X and Y, where X has more data points than Y. So, to be able to compute MIC/TIC both variables must have the same number of data points. As a turn around, could be possible to pad Y with zeros without causing an incorrect estimation of MIC/TIC? Or, do you suggest another alternative?

Many thanks,

Ivan

**Comment by davidealbanese** [comment]
Dear @ivan-marroquin,

probably you would downsample both X and Y to the same size (e.g. https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.decimate.html)

**Comment by ivan-marroquin** [comment]
Hi @davidealbanese ,

Many thanks for the suggestion!

Ivan
