### ISSUE TITLE
Matlab

### ISSUE THREAD

**Issue by ta12162** [minepy/minepy#25]
Hey, 
Sorry to bother. 
For the Matlab integration, how do you ensure that Matlab reads the .c file as I keep getting this error message: Undefined function or variable 'mine_mex'
What I did was to unzip both mine.m and mine_mex.c and call mine as a function? Should this be done differently? 
Kindly
Thanks

**Comment by davidealbanese** [comment]
Dear @ta12162,

[here](https://minepy.readthedocs.io/en/latest/install.html#matlab-users-windows-linux-and-mac-os-x) you can find the steps needed to install the library in Matlab.

**Comment by ta12162** [comment]
Dear David, sorry for the late reply, thanks a lot. T
