### ISSUE TITLE
Python 3.9 incompatibility

### ISSUE THREAD

**Issue by philip-khor** [minepy/minepy#26]
Conda-forge python 3.9 builds seem to be failing because 

> The tp_print slot of PyTypeObject has been removed. 

Seeing this error in build logs (https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/222714/logs/95): 

>   minepy/mine.c:7856:33: error: no member named 'tp_print' in 'struct _typeobject'

See also conda-forge/minepy-feedstock#3

**Comment by davidealbanese** [comment]
Related to https://github.com/cython/cython/pull/3186#issue-327864956.

**Comment by davidealbanese** [comment]
Fixed in version 1.2.5.
