### ISSUE TITLE
compute_score latency?

### ISSUE THREAD

**Issue by nickhuangxinyu** [minepy/minepy#27]
i use minepy to calculate mic between x and y

when x shape is 3w, cost 21s

when size reaches 30w, cost a long long time.

Is this normal? or i used it in the wrong way?

```
from minepy import MINE
m=MINE()
res=m.compute(df['x'], df['y'])  # len(df)=30w, it cost a really long time
print(res.mic())
```

**Comment by davidealbanese** [comment]
Dear @nickhuangxinyu,
I don't understand what "3w",  "30w" and "long time" mean. Could you be more precise?

**Comment by nickhuangxinyu** [comment]
ok, my fault, 30w is a lanuage usage in chinese :(

I have a pandas dataframe, length=300000, it have two columns, ['x', 'y']

and my code is:

```
from minepy import MINE
import time
s=time.time()
m=MINE()
res=m.compute(df['x'], df['y'])  # len(df)=300000, it cost a really long time
print(res.mic(), 'cost', time.time()-s)
```

it cost me 300s to get the result.

so, i want to know, is there mistake i made to make the running time so long? or it just cost that many times to calculate because the algorithm is complex?

i
