### ISSUE TITLE
What the mean of the B parameter?

### ISSUE THREAD

**Issue by GF-Huang** [minepy/minepy#28]
https://minepy.readthedocs.io/en/latest/python.html

> alpha (float (0, 1.0] or >=4) – if alpha is in (0,1] then B will be max(n^alpha, 4) where n is the number of samples. If alpha is >=4 then alpha defines directly the B parameter. If alpha is higher than the number of samples (n) it will be limited to be n, so B = min(alpha, n).

**Comment by davidealbanese** [comment]
B(n) is the maximum grid size (xy). For example, if B=9 the mine algorithm can use grids 2x2, 2x3, 3x2, 3x3, 4x2 and 2x4. If the parameter `alpha` in minepy is set in (0,1] then B will be max(n^alpha, 4) (i.e. is function of sample size), whereas if `alpha` is >=4 then it defines directly B.

**Comment by GF-Huang** [comment]
Thanks clarify.

**Comment by GF-Huang** [comment]
@davidealbanese Hi, what's the diff between `mic_approx` and `mic_e`? In other words, what's the diff of `original` and `equicharacteristic`?
