### ISSUE TITLE
Requires setuptools<58

### ISSUE THREAD

**Issue by philip-khor** [minepy/minepy#32]
FYI that use_2to3 seems to have been depreciated in setuptools 58. 

https://github.com/minepy/minepy/blob/6b0570f4f9538af3554dcb56856d525584bb5f03/setup.py#L54

Please see for instance griffithlab/pVACtools#712.

**Comment by davidealbanese** [comment]
Dear @philip-khor, thanks

**Comment by zzdzzdzzdzzd** [comment]
Please update minepy package for Python 3.11. Thanks.
