### ISSUE TITLE
intel_fast_memset

### ISSUE THREAD

**Issue by emaddy0420** [minepy/minepy#8]
I'm having trouble installing and running the examples using anaconda2/python2.7.  I seem to have all requirements met, but I am receiving the error: 

python minepy_test.py 
Traceback (most recent call last):
  File "minepy_test.py", line 4, in <module>
    from minepy import MINE
  File "/data/users/emaddy/anaconda2/lib/python2.7/site-packages/minepy/**init**.py", line 1, in <module>
    from .mine import MINE
ImportError: /data/users/emaddy/anaconda2/lib/python2.7/site-packages/minepy/mine.so: undefined symbol: _intel_fast_memset

Any help to debug this issue would be appreciated.
Thanks

**Comment by davidealbanese** [comment]
Probably related to the anaconda minepy package.
